site_name: Portfolio
site_author: Hubert Skwarliński
site_description: Data Scientist | AI Developer | ML Engineer - Portfolio zawodowe
site_url: https://skwarlinski.github.io/portfolio/

theme:
  name: material
  language: pl
  palette:
    # Tryb jasny
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Przełącz na tryb ciemny
    # Tryb ciemny
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Przełącz na tryb jasny
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

# Repository
repo_name: skwarlinski/portfolio
repo_url: https://github.com/skwarlinski/portfolio

# Navigation
nav:
  - Strona główna: index.md
  - Projekty:
    - 💻 Aplikacje:
      - Zaplanuj.to: zaplanuj_to/index.md
      - Chat AI: chat-ai/index.md
      - AI Półmaraton: ai-polmaraton/index.md
      - Find Friends: find-friends/index.md
      - Audio Notes: audio-notes/index.md
    - 📈 Analizy EDA:
      - Iris: iris/index.md
      - Titanic: titanic/index.md
  - Kontakt: kontakt.md

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - search:
      lang: en

# Extra
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hubert-skwarlinski-895437368/
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/skwarlinski
      name: GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:skwarlinskihubert@gmail.com
      name: Email

# Copyright
copyright: Copyright &copy; 2024 Hubert Skwarliński